version: "3.8"
services:
  db:
    container_name: mysql
    build: ./db
    image: 1m0gen/trio-task-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
    volumes:
    - type: volume
      source: trio-task-db
      target: /var/lib/mysql
  flask-app:
    container_name: flask-app
    build: ./flask-app
    image: 1m0gen/trio-task-flask-app
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  trio-task-db: